# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3e06d22c02058a13afcbbe7cf812052b0ef8208caada078c15541d8da8fd51fe6a1ff5bbfc9f4128a32887024079b22ddc6b776acb17db9245d95bc9ea2305b2

test:
  secret_key_base: 7a4f55328956b54d63118f032ca6463e4906cad1cb8195ff65239802e0ea8881ebb95ca92e22863605beae1c3824e9e51385b0a462d277229d6516c72204be5b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
